# Generated by Django 3.2.8 on 2021-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrAgenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_qr', models.ImageField(upload_to='qr')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Qr',
                'verbose_name_plural': 'Qrs',
            },
        ),
    ]
