# Generated by Django 3.2.8 on 2021-12-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del local')),
                ('direccion', models.CharField(max_length=200, unique=True, verbose_name='Dirección del local')),
                ('contacto', models.IntegerField(verbose_name='Conatcto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('imagen', models.URLField(max_length=255)),
                ('aforo_maximo', models.PositiveIntegerField(verbose_name='Aforo Maximo')),
                ('aforo_actual', models.PositiveIntegerField(default=0, verbose_name='Aforo actual')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='TipoReclamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoria de reclamo',
                'verbose_name_plural': 'Categorias de reclamos',
            },
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('asignado', models.BooleanField(default=False, verbose_name='Asignado')),
                ('descripcion_personal', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción del personal')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='fecha de actualización')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='local.tiporeclamo')),
                ('personal_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Reaclamo y Sugerencia',
                'verbose_name_plural': 'Reaclamos y Sugerencias',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='fecha de actualización')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.hora')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
