# Generated by Django 3.2.8 on 2021-10-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=200, unique=True, verbose_name='direccion')),
                ('contacto', models.IntegerField(verbose_name='conatcto')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='TipoReclamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoria de reclamo',
                'verbose_name_plural': 'Categorias de reclamos',
            },
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('asignado', models.BooleanField(default=False, verbose_name='Asignado')),
                ('descripcion_personal', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción del personal')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='fecha de actualización')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.tiporeclamo')),
                ('personal_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Reaclamo y Sugerencia',
                'verbose_name_plural': 'Reaclamos y Sugerencias',
            },
        ),
    ]
